### ISSUE TITLE
DataWeave Modules missing from the list

### ISSUE THREAD

**Issue by alexandramartinez** [mulesoft/docs-dataweave#193]
On the left-hand rail, I can see way more modules that are not listed under [DataWeave Modules](https://docs.mulesoft.com/dataweave/latest/dw-functions#dw_modules). I wasn't sure how to add these to the list because of the formatting that's being used in markdown, but this is the list of the missing modules:

- Dates
- Numbers
- Periods
- Types
- DataFormat
- Multipart
- Mule
- Coercions
- Math
- Timer
- Tree
- Values

**Comment by dukesphere** [comment]
thx @alexandramartinez 
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000015spc2YAA/view

**Comment by dmerlob** [comment]
PR created to add the missing modules.
https://github.com/mulesoft/docs-dataweave/pull/195

**Comment by dukesphere** [comment]
closing, as this is fixed.

Thx for submitting the issue, @alexandramartinez
