### ISSUE TITLE
W-12522910: Wrong number of columns for parameter notTruncateDependingOnSubjectNotPresent - modules/ROOT/pages/_partials/dataweave-formats-flatfile-config.adoc

### ISSUE THREAD

**Issue by AndyDaSilva52** [mulesoft/docs-dataweave#245]
The documentation: [Flat File Format | MuleSoft Documentation](https://docs.mulesoft.com/dataweave/2.4/dataweave-formats-flatfile#writer_properties) has some issue in a table.

The new parameter `notTruncateDependingOnSubjectNotPresent` was documented with **3** columns, and the it expect **4** columns.

- https://github.com/mulesoft/docs-dataweave/commit/e0e9cf3fe7a2714b6b723e34ca88a17b80417b8f

![image](https://user-images.githubusercontent.com/1809812/217957306-7922755f-b3f6-4c72-9926-432db66660fb.png)

@dukesphere can you look at this and help getting fix. Tks

**Comment by dukesphere** [comment]
Thanks for the heads up, @AndyDaSilva52 . We will fix it asap. :)

**Comment by dukesphere** [comment]
This issue has been resolved, and the fix should be published on 2/10.

**Comment by dukesphere** [comment]
This issue has been resolved, and the fix should be published on 2/10 after the doc build.

Merge was https://github.com/mulesoft/docs-dataweave/pull/246/files.
