### ISSUE TITLE
Add XML examples for the 'update' function

### ISSUE THREAD

**Issue by arch-jn** [mulesoft/docs-dataweave#268]
[update](https://docs.mulesoft.com/dataweave/2.4/dw-values-functions-update) function page doesn't cover any XML examples or complex examples such as how to update a specific element that doesn't have a unique field name.
It took me some time to figure those out myself so I would like to add it to the documentation to help the next person.

**Comment by dukesphere** [comment]
We are closing this issue because PR #270 was created for it.
